name: Deploy Dev

on:
  push:
    branches: ["dev/master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: .env setting
        run: |
          echo "NEXT_PUBLIC_KAKAO_RESTAPI=${{ secrets.NEXT_PUBLIC_KAKAO_RESTAPI }}" >> .env
          echo "NEXT_PUBLIC_REDIRECTURI=${{ secrets.NEXT_PUBLIC_REDIRECTURI }}" >> .env
        
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn devbuild

      - name: S3 Deploy
        run: aws s3 sync ./out s3://siksha-dev.wafflestudio.com/ --acl bucket-owner-full-control
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.NEXT_PUBLIC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.NEXT_PUBLIC_AWS_CF_DISTRIBUTION_ID_DEV}}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUD_FRONT_ID --paths /*